
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.Timer;



public class CreateProfile extends javax.swing.JFrame {

    public CreateProfile() {
        initComponents();
        jLabelComplete.setVisible(false);
    }

    ArrayList<Player> players = new ArrayList<>();
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelCreate = new javax.swing.JPanel();
        jlabelName = new javax.swing.JLabel();
        jtextboxName = new javax.swing.JTextField();
        jlabelChips = new javax.swing.JLabel();
        jsliderChips = new javax.swing.JSlider();
        jbuttonSubmit = new javax.swing.JButton();
        jbuttonBack = new javax.swing.JButton();
        jLabelComplete = new javax.swing.JLabel();
        jlabeltitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);

        jpanelCreate.setBackground(new java.awt.Color(80, 120, 1));
        jpanelCreate.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jlabelName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jlabelName.setText("Enter Players Name:");
        jlabelName.setToolTipText("");
        jlabelName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtextboxName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtextboxName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtextboxName.setToolTipText("");
        jtextboxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextboxNameActionPerformed(evt);
            }
        });

        jlabelChips.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jlabelChips.setText("Choose Starting Amount:");
        jlabelChips.setToolTipText("");
        jlabelChips.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jsliderChips.setBackground(new java.awt.Color(255, 255, 255));
        jsliderChips.setFont(new java.awt.Font("Tunga", 0, 24)); // NOI18N
        jsliderChips.setForeground(new java.awt.Color(0, 0, 0));
        jsliderChips.setMajorTickSpacing(100);
        jsliderChips.setMaximum(1500);
        jsliderChips.setMinorTickSpacing(50);
        jsliderChips.setPaintLabels(true);
        jsliderChips.setPaintTicks(true);
        jsliderChips.setSnapToTicks(true);
        jsliderChips.setToolTipText("Starting Chip Count");
        jsliderChips.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsliderChips.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsliderChips.setName("ChipSlider"); // NOI18N

        jbuttonSubmit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jbuttonSubmit.setText("Submit");
        jbuttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSubmitActionPerformed(evt);
            }
        });

        jbuttonBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jbuttonBack.setText("Back to Menu");
        jbuttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonBackActionPerformed(evt);
            }
        });

        jLabelComplete.setFont(new java.awt.Font("Razer Text Regular", 1, 60)); // NOI18N
        jLabelComplete.setText("PROFILE CREATED");

        jlabeltitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 60)); // NOI18N
        jlabeltitle.setForeground(new java.awt.Color(255, 255, 255));
        jlabeltitle.setText("PLAYER ACCOUNT CREATION");
        jlabeltitle.setToolTipText("");
        jlabeltitle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpanelCreateLayout = new javax.swing.GroupLayout(jpanelCreate);
        jpanelCreate.setLayout(jpanelCreateLayout);
        jpanelCreateLayout.setHorizontalGroup(
            jpanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelCreateLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(jpanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelCreateLayout.createSequentialGroup()
                        .addComponent(jlabelName)
                        .addGap(53, 53, 53)
                        .addComponent(jtextboxName, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(841, 841, 841))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelCreateLayout.createSequentialGroup()
                        .addComponent(jLabelComplete)
                        .addGap(65, 65, 65)))
                .addGap(31, 31, 31))
            .addGroup(jpanelCreateLayout.createSequentialGroup()
                .addGroup(jpanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCreateLayout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(jlabelChips))
                    .addGroup(jpanelCreateLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jpanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabeltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsliderChips, javax.swing.GroupLayout.PREFERRED_SIZE, 1277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuttonSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jpanelCreateLayout.setVerticalGroup(
            jpanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelCreateLayout.createSequentialGroup()
                .addGroup(jpanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelCreateLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCreateLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jlabeltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                        .addGroup(jpanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtextboxName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119)
                        .addComponent(jlabelChips, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jpanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCreateLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jsliderChips, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelCreateLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    // Save Profiles
    public static void SaveProfiles(ArrayList<Player> profiles) throws IOException{
	
        for(int i = 0; i < profiles.size(); i++){
			FileOutputStream fos = new FileOutputStream("profiles.txt");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(profiles);
			oos.close();
		}
		
	}
   
    private ArrayList<Player> ReadFile() throws FileNotFoundException, IOException, ClassNotFoundException{
    
    FileInputStream read = new FileInputStream("profiles.txt");
	ObjectInputStream ois = new ObjectInputStream(read);	
	ArrayList<Player> playerList = (ArrayList<Player>) ois.readObject();
        ois.close();
        
        return playerList;
    }
    
    // Creating Player
    private void jbuttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSubmitActionPerformed
        String name = jtextboxName.getText();
        double sliderval = jsliderChips.getValue();
        int startingchip = (int)(sliderval);
        boolean show = true;
        
        // try catch to read the file with players already on it
        try {
            players = ReadFile();
        } 
        catch (IOException | ClassNotFoundException ex) {}
        
        players.add(new Player(name, startingchip));
        // try catch for saving the new lsit
        try {
          SaveProfiles(players);
	} 
        catch (IOException e) {
        }
        
        // --------------------- Profile Created Label -----------------------
        jLabelComplete.setVisible(show);
        // https://stackoverflow.com/questions/1006611/java-swing-timer 
        ActionListener RemoveCompletion = (ActionEvent evt1) -> {
            if (show == true){
                jLabelComplete.setVisible(false);
            }
        };
        Timer timer = new Timer(1500 ,RemoveCompletion);
        timer.setRepeats(false);
        timer.start();
        // ----------------End of Profile Created Label ---------------------
    }//GEN-LAST:event_jbuttonSubmitActionPerformed

    
    //Quit to Menu
    private void jbuttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonBackActionPerformed
        new MainWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbuttonBackActionPerformed

    //Accidental Misclick
    private void jtextboxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextboxNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextboxNameActionPerformed

    
    // -------------------------------- Start of Main --------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateProfile().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelComplete;
    private javax.swing.JButton jbuttonBack;
    private javax.swing.JButton jbuttonSubmit;
    private javax.swing.JLabel jlabelChips;
    private javax.swing.JLabel jlabelName;
    private javax.swing.JLabel jlabeltitle;
    private javax.swing.JPanel jpanelCreate;
    private javax.swing.JSlider jsliderChips;
    private javax.swing.JTextField jtextboxName;
    // End of variables declaration//GEN-END:variables
}
