
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Laird99
 */
public class DeleteProfile extends javax.swing.JFrame {

    /**
     * Creates new form DeleteProfile
     */
    public DeleteProfile() {
        initComponents();
        jlabelusermsg.setVisible(false);
        AttemptLoad();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDelete = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonDelete = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jlabelInfo = new javax.swing.JLabel();
        jlabelinfo1 = new javax.swing.JLabel();
        jlabelinfo2 = new javax.swing.JLabel();
        jlabelinfo3 = new javax.swing.JLabel();
        jlabelusermsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanelDelete.setBackground(new java.awt.Color(80, 120, 1));
        jPanelDelete.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jList1.setFont(new java.awt.Font("Kalinga", 0, 30)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Names Go Here" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jButtonDelete.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jButtonDelete.setText("DELETE PROFILE");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jButtonBack.setText("BACK TO MENU");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jlabelInfo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlabelInfo.setForeground(new java.awt.Color(255, 102, 0));
        jlabelInfo.setText("INSTRUCTIONS");

        jlabelinfo1.setFont(new java.awt.Font("Meiryo UI", 3, 24)); // NOI18N
        jlabelinfo1.setText("Select profile from the list and press the delete button. ");

        jlabelinfo2.setFont(new java.awt.Font("Meiryo UI", 3, 24)); // NOI18N
        jlabelinfo2.setText("Only one profile can be deleted at a time.");

        jlabelinfo3.setFont(new java.awt.Font("Meiryo UI", 3, 24)); // NOI18N
        jlabelinfo3.setForeground(new java.awt.Color(204, 0, 0));
        jlabelinfo3.setText("WARNING - Ensure correct profile is selected, all deletions are permanent.");

        jlabelusermsg.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jlabelusermsg.setForeground(new java.awt.Color(204, 0, 0));
        jlabelusermsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelusermsg.setToolTipText("");

        javax.swing.GroupLayout jPanelDeleteLayout = new javax.swing.GroupLayout(jPanelDelete);
        jPanelDelete.setLayout(jPanelDeleteLayout);
        jPanelDeleteLayout.setHorizontalGroup(
            jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeleteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(jlabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlabelinfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelinfo1)
                            .addComponent(jlabelinfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeleteLayout.createSequentialGroup()
                        .addGroup(jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                                .addComponent(jlabelusermsg, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                                .addGap(374, 374, 374)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65))))
        );
        jPanelDeleteLayout.setVerticalGroup(
            jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jlabelInfo)
                .addGap(32, 32, 32)
                .addComponent(jlabelinfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jlabelinfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabelinfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jlabelusermsg, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private ArrayList<Player> players = new ArrayList<>();
    
    private void AttemptLoad(){
        String[] names = new String[50];
        try {
            players = LoadProfiles();
        } 
        catch (FileNotFoundException e) {}
        catch (IOException | ClassNotFoundException e) {}
        
        for(int i = 0; i < players.size(); i++){
        
            names[i] = "<html>" + players.get(i).GetUser() + "<br>";
        }
        
        jList1.setListData(names);
    }
    
    public static ArrayList<Player> LoadProfiles() throws FileNotFoundException, IOException, ClassNotFoundException{
		FileInputStream fis = new FileInputStream("profiles.txt");
		ObjectInputStream ois = new ObjectInputStream(fis);
		ArrayList<Player> playerList = (ArrayList<Player>) ois.readObject();
		ois.close();
		
		return playerList;
	}
    
    public static void SaveProfiles(ArrayList<Player> profiles) throws IOException{
	
        for(int i = 0; i < profiles.size(); i++){
            FileOutputStream fos = new FileOutputStream("profiles.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(profiles);
            oos.close();
        }
		
    }
    
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
    String p1 = jList1.getSelectedValue();
    if(p1 == null){
        jlabelusermsg.setText("PLEASE SELECT A PROFILE TO DELETE");
        jlabelusermsg.setVisible(true);
    }  
    
    else{
        for (int y = 0; y < players.size(); y++) {
        String content = "<html>" + players.get(y).GetUser() + "<br>";
        System.out.print(content + " " + p1 + "\n");    
            if(content.equals(p1)){
                players.remove(y);
            }
            else{
            try {
                SaveProfiles(players);
            } catch (IOException ex) {}
            }
        }
        
        new MainWindow().setVisible(true);
        this.setVisible(false);
    
    }
    
    
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        new MainWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanelDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabelInfo;
    private javax.swing.JLabel jlabelinfo1;
    private javax.swing.JLabel jlabelinfo2;
    private javax.swing.JLabel jlabelinfo3;
    private javax.swing.JLabel jlabelusermsg;
    // End of variables declaration//GEN-END:variables
}
