
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;

public class LoadProfile extends javax.swing.JFrame {

    public LoadProfile() {
        initComponents();
        jlabelretry.setVisible(false);
        AttemptLoad();
    }

    private ArrayList<Player> players = new ArrayList<>();
    
    private void AttemptLoad(){
        String[] content = new String[50];
        try {
            players = LoadProfiles();
        } 
        catch (FileNotFoundException e) {}
        catch (IOException | ClassNotFoundException e) {}
        
        for(int i = 0; i < players.size(); i++){
        
            content[i] = "<html>" + players.get(i).GetUser() + "<br>";      
        }
        
        jListPlayers.setListData(content);
    }
    
    public static ArrayList<Player> LoadProfiles() throws FileNotFoundException, IOException, ClassNotFoundException{
		FileInputStream fis = new FileInputStream("profiles.txt");
		ObjectInputStream ois = new ObjectInputStream(fis);
		ArrayList<Player> playerList = (ArrayList<Player>) ois.readObject();
		ois.close();
		
		return playerList;
	}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelLoad = new javax.swing.JPanel();
        jButtonPlay = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jlabelInfo = new javax.swing.JLabel();
        jlabelinfo2 = new javax.swing.JLabel();
        jlabelinfo1 = new javax.swing.JLabel();
        jlabelinfo3 = new javax.swing.JLabel();
        jlabelretry = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPlayers = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        jpanelLoad.setBackground(new java.awt.Color(80, 120, 1));
        jpanelLoad.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jButtonPlay.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jButtonPlay.setText("Load and Play");
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });

        jButtonMenu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jButtonMenu.setText("Back to Menu");
        jButtonMenu.setToolTipText("");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        jlabelInfo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlabelInfo.setForeground(new java.awt.Color(255, 102, 0));
        jlabelInfo.setText("INSTRUCTIONS");

        jlabelinfo2.setFont(new java.awt.Font("Meiryo UI", 3, 24)); // NOI18N
        jlabelinfo2.setText("Profile has to be selected to advance, if not game will not start.");

        jlabelinfo1.setFont(new java.awt.Font("Meiryo UI", 3, 24)); // NOI18N
        jlabelinfo1.setText("Select profile from the list and press load to begin. ");

        jlabelinfo3.setFont(new java.awt.Font("Meiryo UI", 3, 24)); // NOI18N
        jlabelinfo3.setForeground(new java.awt.Color(204, 0, 0));
        jlabelinfo3.setText("WARNING - Without profile, player can only return to main menu");

        jlabelretry.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jlabelretry.setForeground(new java.awt.Color(204, 0, 0));
        jlabelretry.setText("PLEASE SELECT A VALID PROFILE AND RETRY!");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jListPlayers.setFont(new java.awt.Font("Kalinga", 0, 30)); // NOI18N
        jListPlayers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Names will go here" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListPlayers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListPlayers.setToolTipText("");
        jScrollPane2.setViewportView(jListPlayers);

        javax.swing.GroupLayout jpanelLoadLayout = new javax.swing.GroupLayout(jpanelLoad);
        jpanelLoad.setLayout(jpanelLoadLayout);
        jpanelLoadLayout.setHorizontalGroup(
            jpanelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLoadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addGroup(jpanelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLoadLayout.createSequentialGroup()
                            .addComponent(jlabelinfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(254, 254, 254))
                        .addGroup(jpanelLoadLayout.createSequentialGroup()
                            .addGroup(jpanelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlabelinfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlabelinfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(233, 233, 233)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLoadLayout.createSequentialGroup()
                        .addComponent(jlabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(492, 492, 492))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLoadLayout.createSequentialGroup()
                        .addComponent(jButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLoadLayout.createSequentialGroup()
                        .addComponent(jlabelretry, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );
        jpanelLoadLayout.setVerticalGroup(
            jpanelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLoadLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jpanelLoadLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jlabelInfo)
                .addGap(18, 18, 18)
                .addComponent(jlabelinfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelinfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabelinfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(jlabelretry, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelLoad, javax.swing.GroupLayout.DEFAULT_SIZE, 2136, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelLoad, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        new MainWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        String p1 = jListPlayers.getSelectedValue();
        int chipcount = 0;
        int chipLoc;
        if(p1 == null){
            jlabelretry.setVisible(true);
        }
        
        else{
            for (int y = 0; y < players.size(); y++) {
                String content = "<html>" + players.get(y).GetUser() + "<br>";
                if(content.equals(p1)){
                    chipcount = players.get(y).GetChips();
                }
            }
            new Game(p1, chipcount).setVisible(true);
            this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_jButtonPlayActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadProfile().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JList<String> jListPlayers;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabelInfo;
    private javax.swing.JLabel jlabelinfo1;
    private javax.swing.JLabel jlabelinfo2;
    private javax.swing.JLabel jlabelinfo3;
    private javax.swing.JLabel jlabelretry;
    private javax.swing.JPanel jpanelLoad;
    // End of variables declaration//GEN-END:variables
}
